### ISSUE TITLE
MongoError: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by radu-m** [HODL-DAO/ELTBOT20#9]
The DB crashed with following log:
```
 ➜      heroku logs --app=eltbot20
2020-12-20T04:36:48.944435+00:00 app[web.1]: at TLSSocket.emit (events.js:210:5) {
2020-12-20T04:36:48.944436+00:00 app[web.1]: driver: true,
2020-12-20T04:36:48.944436+00:00 app[web.1]: name: 'MongoError',
2020-12-20T04:36:48.944441+00:00 app[web.1]: index: 0,
2020-12-20T04:36:48.944441+00:00 app[web.1]: code: 11000,
2020-12-20T04:36:48.944441+00:00 app[web.1]: keyPattern: { chatId: 1 },
2020-12-20T04:36:48.944442+00:00 app[web.1]: keyValue: { chatId: -1001139141757 }
2020-12-20T04:36:48.944442+00:00 app[web.1]: }
2020-12-20T04:36:48.967448+00:00 app[web.1]: WRONG! ERR:  MongoError: E11000 duplicate key error collection: <dbname>.users index: chatId_1 dup key: { chatId: -1001139141757.0 }
2020-12-20T04:36:48.967451+00:00 app[web.1]: at Function.create (/app/node_modules/mongodb/lib/core/error.js:57:12)
2020-12-20T04:36:48.967451+00:00 app[web.1]: at toError (/app/node_modules/mongodb/lib/utils.js:123:22)
2020-12-20T04:36:48.967452+00:00 app[web.1]: at /app/node_modules/mongodb/lib/operations/common_functions.js:265:39
2020-12-20T04:36:48.967452+00:00 app[web.1]: at handler (/app/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
2020-12-20T04:36:48.967456+00:00 app[web.1]: at /app/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
2020-12-20T04:36:48.967457+00:00 app[web.1]: at handleOperationResult (/app/node_modules/mongodb/lib/core/sdam/server.js:558:5)
2020-12-20T04:36:48.967457+00:00 app[web.1]: at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:277:5)
2020-12-20T04:36:48.967458+00:00 app[web.1]: at MessageStream.emit (events.js:210:5)
2020-12-20T04:36:48.967458+00:00 app[web.1]: at MessageStream.EventEmitter.emit (domain.js:476:20)
2020-12-20T04:36:48.967459+00:00 app[web.1]: at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2020-12-20T04:36:48.967459+00:00 app[web.1]: at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
2020-12-20T04:36:48.967459+00:00 app[web.1]: at doWrite (_stream_writable.js:431:12)
2020-12-20T04:36:48.967460+00:00 app[web.1]: at writeOrBuffer (_stream_writable.js:415:5)
2020-12-20T04:36:48.967460+00:00 app[web.1]: at MessageStream.Writable.write (_stream_writable.js:305:11)
2020-12-20T04:36:48.967461+00:00 app[web.1]: at TLSSocket.ondata (_stream_readable.js:726:22)
2020-12-20T04:36:48.967461+00:00 app[web.1]: at TLSSocket.emit (events.js:210:5) {
2020-12-20T04:36:48.967462+00:00 app[web.1]: driver: true,
2020-12-20T04:36:48.967463+00:00 app[web.1]: name: 'MongoError',
2020-12-20T04:36:48.967463+00:00 app[web.1]: index: 0,
2020-12-20T04:36:48.967464+00:00 app[web.1]: code: 11000,
2020-12-20T04:36:48.967464+00:00 app[web.1]: keyPattern: { chatId: 1 },
2020-12-20T04:36:48.967465+00:00 app[web.1]: keyValue: { chatId: -1001139141757 }
2020-12-20T04:36:48.967465+00:00 app[web.1]: }
2020-12-20T04:36:48.973854+00:00 app[web.1]: WRONG! ERR:  MongoError: E11000 duplicate key error collection: <dbname>.users index: chatId_1 dup key: { chatId: -1001139141757.0 }
2020-12-20T04:36:48.973856+00:00 app[web.1]: at Function.create (/app/node_modules/mongodb/lib/core/error.js:57:12)
2020-12-20T04:36:48.973857+00:00 app[web.1]: at toError (/app/node_modules/mongodb/lib/utils.js:123:22)
2020-12-20T04:36:48.973857+00:00 app[web.1]: at /app/node_modules/mongodb/lib/operations/common_functions.js:265:39
2020-12-20T04:36:48.973858+00:00 app[web.1]: at handler (/app/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
2020-12-20T04:36:48.973858+00:00 app[web.1]: at /app/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
2020-12-20T04:36:48.973859+00:00 app[web.1]: at handleOperationResult (/app/node_modules/mongodb/lib/core/sdam/server.js:558:5)
2020-12-20T04:36:48.973859+00:00 app[web.1]: at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:277:5)
2020-12-20T04:36:48.973860+00:00 app[web.1]: at MessageStream.emit (events.js:210:5)
2020-12-20T04:36:48.973860+00:00 app[web.1]: at MessageStream.EventEmitter.emit (domain.js:476:20)
2020-12-20T04:36:48.973861+00:00 app[web.1]: at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2020-12-20T04:36:48.973861+00:00 app[web.1]: at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
2020-12-20T04:36:48.973862+00:00 app[web.1]: at doWrite (_stream_writable.js:431:12)
2020-12-20T04:36:48.973862+00:00 app[web.1]: at writeOrBuffer (_stream_writable.js:415:5)
2020-12-20T04:36:48.973863+00:00 app[web.1]: at MessageStream.Writable.write (_stream_writable.js:305:11)
2020-12-20T04:36:48.973863+00:00 app[web.1]: at TLSSocket.ondata (_stream_readable.js:726:22)
2020-12-20T04:36:48.973864+00:00 app[web.1]: at TLSSocket.emit (events.js:210:5) {
2020-12-20T04:36:48.973864+00:00 app[web.1]: driver: true,
2020-12-20T04:36:48.973865+00:00 app[web.1]: name: 'MongoError',
2020-12-20T04:36:48.973865+00:00 app[web.1]: index: 0,
2020-12-20T04:36:48.973866+00:00 app[web.1]: code: 11000,
2020-12-20T04:36:48.973866+00:00 app[web.1]: keyPattern: { chatId: 1 },
2020-12-20T04:36:48.973866+00:00 app[web.1]: keyValue: { chatId: -1001139141757 }
2020-12-20T04:36:48.973867+00:00 app[web.1]: }
2020-12-20T04:36:48.980314+00:00 app[web.1]: WRONG! ERR:  MongoError: E11000 duplicate key error collection: <dbname>.users index: chatId_1 dup key: { chatId: -1001139141757.0 }
2020-12-20T04:36:48.980317+00:00 app[web.1]: at Function.create (/app/node_modules/mongodb/lib/core/error.js:57:12)
2020-12-20T04:36:48.980317+00:00 app[web.1]: at toError (/app/node_modules/mongodb/lib/utils.js:123:22)
2020-12-20T04:36:48.980318+00:00 app[web.1]: at /app/node_modules/mongodb/lib/operations/common_functions.js:265:39
2020-12-20T04:36:48.980318+00:00 app[web.1]: at handler (/app/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
2020-12-20T04:36:48.980319+00:00 app[web.1]: at /app/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
2020-12-20T04:36:48.980319+00:00 app[web.1]: at handleOperationResult (/app/node_modules/mongodb/lib/core/sdam/server.js:558:5)
2020-12-20T04:36:48.980320+00:00 app[web.1]: at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:277:5)
2020-12-20T04:36:48.980321+00:00 app[web.1]: at MessageStream.emit (events.js:210:5)
2020-12-20T04:36:48.980321+00:00 app[web.1]: at MessageStream.EventEmitter.emit (domain.js:476:20)
2020-12-20T04:36:48.980322+00:00 app[web.1]: at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2020-12-20T04:36:48.980322+00:00 app[web.1]: at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
2020-12-20T04:36:48.980322+00:00 app[web.1]: at doWrite (_stream_writable.js:431:12)
2020-12-20T04:36:48.980323+00:00 app[web.1]: at writeOrBuffer (_stream_writable.js:415:5)
2020-12-20T04:36:48.980323+00:00 app[web.1]: at MessageStream.Writable.write (_stream_writable.js:305:11)
2020-12-20T04:36:48.980324+00:00 app[web.1]: at TLSSocket.ondata (_stream_readable.js:726:22)
2020-12-20T04:36:48.980324+00:00 app[web.1]: at TLSSocket.emit (events.js:210:5) {
2020-12-20T04:36:48.980325+00:00 app[web.1]: driver: true,
2020-12-20T04:36:48.980325+00:00 app[web.1]: name: 'MongoError',
2020-12-20T04:36:48.980326+00:00 app[web.1]: index: 0,
2020-12-20T04:36:48.980326+00:00 app[web.1]: code: 11000,
2020-12-20T04:36:48.980327+00:00 app[web.1]: keyPattern: { chatId: 1 },
2020-12-20T04:36:48.980327+00:00 app[web.1]: keyValue: { chatId: -1001139141757 }
2020-12-20T04:36:48.980328+00:00 app[web.1]: }
2020-12-20T05:12:12.174407+00:00 heroku[web.1]: Idling
2020-12-20T05:12:12.176936+00:00 heroku[web.1]: State changed from up to down
2020-12-20T05:12:13.831927+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-12-20T05:12:14.025264+00:00 heroku[web.1]: Process exited with status 143

```

**Comment by radu-m** [comment]
fixed by : 
```
mongoose.connect(
  process.env.MONGO,
  {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true, // <-- this
    autoIndex: false, // <-- & this
  },
...
```

...as per [related SO thread ](https://github.com/Automattic/mongoose/issues/2471#issuecomment-365042484)
